### ISSUE TITLE
 Ignore_paths works properly?

### ISSUE THREAD

**Issue by ewrvp7lv7** [Ackee-Blockchain/tools-for-solidity-vscode#42]
Thanks for the great job! I'm enjoying!
I'm confused by the output. Are these files ignored or not? I didn't use aragon.
![Screenshot from 2023-02-18 21-05-10](https://user-images.githubusercontent.com/36769374/219870543-9ae4c061-f7ef-4a73-a967-bdf4ddb2f60e.png)

Also, sorry, I didn't clearly understand [how it works](https://github.com/Ackee-Blockchain/tools-for-solidity-vscode#go-to-definition)? I mean how to turn an emit into a link?
And one more question, please. Does this extension use any linters? Can I customize them?

**Comment by michprev** [comment]
Hey @ewrvp7lv7,
thank you for using our extension!

Is there any possibility that the argon files are imported from another npm package and files from that package are imported into your project? Unfortunately, it is not currently possible to generate an import dependency graph that would help here, will add it in the next release. You could try removing the `@argon` directory and see if the project compiles. Also, keep in mind that `ignore_paths` are relative to the root workspace directory opened in VS Code.

You can execute `Go to definition` either using a shortcut (`F12` is the default I think) or by holding `ctrl` (control) and clicking the left mouse button. In order for these features (like `Go to definition`) to work, the project must be successfully compiled at least once after opening a VS Code window (we don't store any build artifacts in our extension).

We are using our own linter/vulnerability and code quality detectors. You can configure them in the `Tools for Solidity -> Detectors` settings category. The current set of active detectors is not documented yet but is printed in the output of the `woke detect` command-line command. `woke` should be installed together with the `Tools for Solidity` extension. If you are missing any vulnerability/code quality detector, suggestions are welcome! :slightly_smiling_face:

**Comment by ewrvp7lv7** [comment]
Thank you! I removed argon and don't see any new errors. Also, I'm trying to ignore the interfaces folder by woke.compiler.solc.ignore_paths and woke.detectors.ignore_paths. I feel like I'm doing everything right. Please check.
![Screenshot from 2023-02-18 23-30-42](https://user-images.githubusercontent.com/36769374/219877324-e3cd8da1-d685-469c-8c75-4c67eee28fb6.png)

**Comment by ewrvp7lv7** [comment]
If there was formatters it would be fine.

**Comment by michprev** [comment]
Thank you, I found an issue regarding diagnostics (compiler warnings and errors) not being cleared after changing `ignore_paths`. It will be fixed in the next release.

As a workaround, VS Code restart should be enough.

**Comment by ewrvp7lv7** [comment]
Its work! Thank you very much!
