### ISSUE TITLE
Make path of woke cli customizable so I can debug woke cli tool easier and submit PRs

### ISSUE THREAD

**Issue by DrakeEvans** [Ackee-Blockchain/tools-for-solidity-vscode#53]
Allow me to use my own custom path (to virtual env) so I can help debug and make PRs to woke repo.  Currently I need to run my own version of the vscode extension to point it to the virtual env version of woke and its really painful

**Comment by michprev** [comment]
Fixed in #54, thank you for the pull request! I will add one more config option - an optional port the extension will try to connect to (if specified). It should make debugging even easier because you can launch woke in a terminal with some logging messages (`woke --debug lsp`).
