### ISSUE TITLE
Exception while running printer control-flow-graph: OSError(30, 'Read-only file system')

### ISSUE THREAD

**Issue by reikodoteth** [Ackee-Blockchain/tools-for-solidity-vscode#76]
Hey, the extension started prompting these errors today.

Running 'wake lsp --port 51049'
[Error - 19:07:59] Exception while running printer control-flow-graph: OSError(30, 'Read-only file system')
[Error - 19:07:59] Exception while running printer imports-graph: OSError(30, 'Read-only file system')
[Error - 19:07:59] Exception while running printer inheritance-graph: OSError(30, 'Read-only file system')

The error notification popup every time I type something.

I've been using the extension for months and it worked perfectly, i changed nothing on my environment.

Running it from a M1 Macbook. Rosetta is installed.

**Comment by DrakeEvans** [comment]
Same issue here.  I only get this while inside of tools for solidity.  If I run the command wake lsp --port from the command line I have no issues

**Comment by reikodoteth** [comment]
Updated eth-wake to `4.4.1` and its resolved now 🥳
